import React, { createContext, useContext, useState, useEffect, useCallback } from 'react'

const TRANSLATIONS = {
  en: {
    appTitle: 'Hospital Manager',
    appSubtitle: 'Bangladesh Hospital Management System',

    'nav.dashboard': 'Dashboard',
    'nav.home': 'Home',
    'nav.emergency': 'Emergency Care',
    'nav.list': 'Hospital List',
    'nav.stats': 'Statistics',
    'nav.create': 'Add Hospital',

    searchPages: 'Search pages...',
    signOut: 'Sign out',
    signingOut: 'Signing out…',

    'emergency.title': 'Find Emergency Care',
    'emergency.subtitle': "Tell us about your situation and we'll show you the best-rated hospitals",
    'emergency.step1': 'Describe your situation',
    'emergency.optional': 'optional',
    'emergency.step2': 'Select problem type',
    'emergency.required': 'required',
    'emergency.textareaPlaceholder': 'Briefly describe what happened or your symptoms (e.g., fell and hurt my arm, having chest pain...)',
    'emergency.findBtn': 'Find Best Hospitals',
    'emergency.findingBtn': 'Finding hospitals...',
    'emergency.selectError': 'Please select your problem type',
    'emergency.connectionError': 'Could not load hospitals. Please check your connection.',
    'emergency.resultsTitle': 'Recommended Hospitals',
    'emergency.resultsSubtitle': 'Showing {total} hospitals for {type} — ranked by doctor quality score',
    'emergency.newSearch': 'New Search',
    'emergency.noResults': 'No hospitals found. Please contact emergency services directly.',
    'emergency.directions': 'Directions',

    'pt.cut.label': 'Cut / Wound',
    'pt.cut.desc': 'Cuts, lacerations, bleeding injuries',
    'pt.neurological.label': 'Neurological',
    'pt.neurological.desc': 'Head injuries, seizures, stroke symptoms',
    'pt.bone.label': 'Bone / Fracture',
    'pt.bone.desc': 'Broken bones, fractures, joint injuries',
    'pt.cardiac.label': 'Cardiac / Heart',
    'pt.cardiac.desc': 'Chest pain, heart attack, palpitations',
    'pt.respiratory.label': 'Respiratory',
    'pt.respiratory.desc': 'Breathing difficulty, asthma, chest tightness',
    'pt.burn.label': 'Burns',
    'pt.burn.desc': 'Heat burns, chemical burns, scalds',
    'pt.maternity.label': 'Maternity / Birth',
    'pt.maternity.desc': 'Labour, delivery complications, pregnancy emergencies',
    'pt.paediatric.label': 'Child / Paediatric',
    'pt.paediatric.desc': 'Infant and child emergencies, high fever in children',
    'pt.poisoning.label': 'Poisoning / Snakebite',
    'pt.poisoning.desc': 'Food poisoning, chemical ingestion, snakebite',
    'pt.cancer.label': 'Cancer / Tumour',
    'pt.cancer.desc': 'Oncology care, tumour treatment, chemotherapy',
    'pt.trauma.label': 'Accident / Trauma',
    'pt.trauma.desc': 'Road accidents, crush injuries, major trauma',
    'pt.other.label': 'Other Emergency',
    'pt.other.desc': 'Fever, dental, eye, or other urgent care',

    'emergency.hotlineTitle': 'Emergency Contacts',
    'emergency.hotline999': 'National Emergency',
    'emergency.hotline16321': 'Health Helpline',
    'emergency.hotline199': 'Fire & Ambulance',
    'emergency.howTitle': 'How It Works',
    'emergency.how1': 'Select your emergency type',
    'emergency.how2': 'We rank hospitals by doctor quality score',
    'emergency.how3': 'Tap Directions to navigate instantly',
    'emergency.trustNote': 'All hospitals are rated by assigned doctors based on patient outcomes.',

    'hl.title': 'Hospital Registry',
    'hl.subtitle': 'Manage and search registered hospitals',
    'hl.searchPlaceholder': 'Search hospitals by name...',
    'hl.hospitalsFound': '{n} hospitals found',
    'hl.showing': 'Showing {shown} of {total} hospitals',
    'hl.page': 'Page {page} / {totalPages}',
    'hl.noResults': 'No hospitals found',
    'hl.noResultsHint': "Try adjusting your search filters to find what you're looking for.",
    'hl.deleteConfirm': 'Are you sure you want to delete this hospital?',

    'filters.title': 'Filters',
    'filters.clearAll': 'Clear all',
    'filters.clearFilters': 'Clear Filters',
    'filters.division': 'Division',
    'filters.allDivisions': 'All Divisions',
    'filters.district': 'District',
    'filters.allDistricts': 'All Districts',
    'filters.upazila': 'Upazila',
    'filters.allUpazilas': 'All Upazilas',
    'filters.type': 'Hospital Type',
    'filters.allTypes': 'All Types',
    'filters.agency': 'Agency',
    'filters.allAgencies': 'All Agencies',
    'filters.ownership': 'Ownership',
    'filters.all': 'All',
    'filters.private': 'Private',
    'filters.public': 'Public',
    'filters.loading': 'Loading filters...',

    'table.hospital': 'Hospital',
    'table.code': 'Code',
    'table.type': 'Type',
    'table.agency': 'Agency',
    'table.division': 'Division',
    'table.district': 'District',
    'table.email': 'Email',
    'table.status': 'Status',
    'table.actions': 'Actions',
    'table.private': 'Private',
    'table.public': 'Public',

    'stats.title': 'Statistics Overview',
    'stats.subtitle': 'Hospital distribution across Bangladesh',
    'stats.refresh': 'Refresh',
    'stats.overview': 'Overview',
    'stats.total': 'Total Hospitals',
    'stats.public': 'Public Hospitals',
    'stats.private': 'Private Hospitals',
    'stats.ofTotal': '% of total',
    'stats.byType': 'By Hospital Type',
    'stats.types': '{n} types',
    'stats.byDivision': 'By Division',
    'stats.divisions': '{n} divisions',
    'stats.colType': 'Type',
    'stats.count': 'Count',
    'stats.share': 'Share',
    'stats.distribution': 'Distribution',
    'stats.colDivision': 'Division',
    'stats.unknown': 'Unknown',
    'stats.noStats': 'No statistics available',

    'create.title': 'Add New Hospital',
    'create.subtitle': 'Register a new hospital to the system',
    's1': 'Basic Information',
    'create.name': 'Hospital Name',
    'create.namePlaceholder': 'Enter hospital name',
    'create.nameBangla': 'Name in Bangla',
    'create.nameBanglaPlaceholder': 'হাসপাতালের নাম',
    'create.code': 'Hospital Code',
    'create.codePlaceholder': 'Unique numeric code',
    'create.email': 'Email Address',
    'create.emailPlaceholder': 'contact@hospital.com',
    's2': 'Classification',
    'create.type': 'Hospital Type',
    'create.typePlaceholder': 'e.g., Medical College Hospital',
    'create.agency': 'Agency',
    'create.agencyPlaceholder': 'e.g., Government, NGO, Private',
    'create.score': 'Admin Quality Score (0–100)',
    'create.scoreHint': 'Doctor-assigned quality rating used to rank this hospital in emergency searches',
    'create.private': 'Private Hospital',
    'create.privateHint': 'Check if this is a privately owned facility',
    's3': 'Emergency Specialties',
    'create.specialtyHint': 'Select the emergency categories this hospital specialises in. These are used to match it during emergency searches.',
    's4': 'Location',
    'create.division': 'Division',
    'create.divisionPlaceholder': 'e.g., Dhaka, Chittagong',
    'create.district': 'District',
    'create.districtPlaceholder': 'Enter district',
    'create.upazila': 'Upazila',
    'create.upazilaPlaceholder': 'Enter upazila',
    'create.city': 'City Corporation',
    'create.paurasava': 'Paurasava',
    'create.union': 'Union',
    'create.applicable': 'If applicable',
    'create.lat': 'Latitude',
    'create.latPlaceholder': 'e.g. 23.8103',
    'create.lng': 'Longitude',
    'create.lngPlaceholder': 'e.g. 90.4125',
    'create.required': '* Required fields',
    'create.submit': 'Create Hospital',
    'create.creating': 'Creating...',
    'create.nameRequired': 'Hospital name is required',
    'create.codeRequired': 'Hospital code is required',
    'create.success': 'Hospital created successfully!',
    'create.failed': 'Failed to create hospital.',

    'modal.editTitle': 'Edit Hospital',
    'modal.viewTitle': 'Hospital Details',
    'modal.basicInfo': 'Basic Information',
    'modal.hospitalName': 'Hospital Name *',
    'modal.nameBangla': 'Name (Bangla)',
    'modal.code': 'Code',
    'modal.email': 'Email',
    'modal.classification': 'Classification',
    'modal.agency': 'Agency',
    'modal.type': 'Type',
    'modal.ownership': 'Ownership',
    'modal.private': 'Private',
    'modal.public': 'Public',
    'modal.location': 'Location',
    'modal.division': 'Division',
    'modal.district': 'District',
    'modal.upazila': 'Upazila',
    'modal.cityCorporation': 'City Corporation',
    'modal.paurasava': 'Paurasava',
    'modal.union': 'Union',
    'modal.coordinates': 'Coordinates',
    'modal.quality': 'Quality Score',
    'modal.adminScore': 'Admin Score (0–100)',
    'modal.record': 'Record',
    'modal.created': 'Created',
    'modal.updated': 'Last Updated',
    'modal.cancel': 'Cancel',
    'modal.save': 'Save Changes',
    'modal.saving': 'Saving...',
    'modal.close': 'Close',
    'modal.viewMap': '🗺️ View on Map',
    'modal.nameRequired': 'Hospital name is required',
    'modal.updatedSuccess': 'Hospital updated successfully!',
    'modal.createdSuccess': 'Hospital created successfully!',
    'modal.failed': 'Failed to save hospital',
    'modal.privateLabel': 'Private Hospital',

    'error.title': 'Something went wrong',
    'error.retry': 'Try again',
    'error.dismiss': 'Dismiss',

    'auth.appTitle': 'Hospital Manager',
    'auth.appSubtitle': 'Bangladesh Hospital Management System',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInSubtitle': 'Sign in to your account to continue',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.signingIn': 'Signing in…',
    'auth.or': 'or',
    'auth.google': 'Continue with Google',
    'auth.connecting': 'Connecting…',
    'auth.noAccount': "Don't have an account?",
    'auth.createOne': 'Create one',
    'auth.createTitle': 'Create account',
    'auth.createSubtitle': 'Register to access the Hospital Manager',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.confirmPassword': 'Confirm password',
    'auth.pwPlaceholder': 'At least 6 characters',
    'auth.creatingAccount': 'Creating account…',
    'auth.hasAccount': 'Already have an account?',
    'auth.signInLink': 'Sign in',
    'auth.footer': 'Bangladesh Hospital Management System',
    'auth.err.fillAll': 'Please fill in all fields.',
    'auth.err.invalidCred': 'Invalid email or password.',
    'auth.err.tooMany': 'Too many failed attempts. Please try again later.',
    'auth.err.fillAllRequired': 'Please fill in all required fields.',
    'auth.err.pwLength': 'Password must be at least 6 characters.',
    'auth.err.pwMatch': 'Passwords do not match.',
    'auth.err.emailExists': 'An account with this email already exists.',
    'auth.err.diffCred': 'An account with this email already exists. Please sign in with your password.',
    'auth.err.googleFail': 'Google sign-in failed. Please try again.',
    'auth.err.loginFail': 'Login failed. Please try again.',
    'auth.err.registerFail': 'Registration failed. Please try again.',
  },

  bn: {
    appTitle: 'হাসপাতাল ম্যানেজার',
    appSubtitle: 'বাংলাদেশ হাসপাতাল ব্যবস্থাপনা সিস্টেম',

    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.home': 'হোম',
    'nav.emergency': 'জরুরি চিকিৎসা',
    'nav.list': 'হাসপাতাল তালিকা',
    'nav.stats': 'পরিসংখ্যান',
    'nav.create': 'হাসপাতাল যোগ',

    searchPages: 'পেজ খুঁজুন...',
    signOut: 'সাইন আউট',
    signingOut: 'সাইন আউট হচ্ছে…',

    'emergency.title': 'জরুরি চিকিৎসা খুঁজুন',
    'emergency.subtitle': 'আপনার সমস্যা জানান এবং আমরা সেরা হাসপাতাল দেখাব',
    'emergency.step1': 'আপনার পরিস্থিতি বর্ণনা করুন',
    'emergency.optional': 'ঐচ্ছিক',
    'emergency.step2': 'সমস্যার ধরন বেছে নিন',
    'emergency.required': 'আবশ্যিক',
    'emergency.textareaPlaceholder': 'সংক্ষেপে বর্ণনা করুন (যেমন: হাতে ব্যথা লাগছে, বুকে ব্যথা...)',
    'emergency.findBtn': 'সেরা হাসপাতাল খুঁজুন',
    'emergency.findingBtn': 'হাসপাতাল খোঁজা হচ্ছে...',
    'emergency.selectError': 'আপনার সমস্যার ধরন বেছে নিন',
    'emergency.connectionError': 'হাসপাতাল লোড করা যায়নি। আপনার সংযোগ পরীক্ষা করুন।',
    'emergency.resultsTitle': 'প্রস্তাবিত হাসপাতাল',
    'emergency.resultsSubtitle': '{type}-এর জন্য {total}টি হাসপাতাল — ডাক্তার স্কোর অনুযায়ী',
    'emergency.newSearch': 'নতুন অনুসন্ধান',
    'emergency.noResults': 'কোনো হাসপাতাল পাওয়া যায়নি। সরাসরি জরুরি সেবায় যোগাযোগ করুন।',
    'emergency.directions': 'দিকনির্দেশনা',

    'pt.cut.label': 'কাটা / ক্ষত',
    'pt.cut.desc': 'কাটা, ছিঁড়ে যাওয়া, রক্তপাতের আঘাত',
    'pt.neurological.label': 'স্নায়বিক',
    'pt.neurological.desc': 'মাথার আঘাত, খিঁচুনি, স্ট্রোকের লক্ষণ',
    'pt.bone.label': 'হাড় / ভাঙা',
    'pt.bone.desc': 'ভাঙা হাড়, ফ্র্যাকচার, জয়েন্টের আঘাত',
    'pt.cardiac.label': 'হৃদরোগ',
    'pt.cardiac.desc': 'বুকে ব্যথা, হার্ট অ্যাটাক, বুক ধড়ফড়',
    'pt.respiratory.label': 'শ্বাসকষ্ট',
    'pt.respiratory.desc': 'শ্বাস নিতে কষ্ট, হাঁপানি, বুক আঁটসাঁট',
    'pt.burn.label': 'পোড়া',
    'pt.burn.desc': 'তাপে পোড়া, রাসায়নিক পোড়া, গরম পানিতে পোড়া',
    'pt.maternity.label': 'মাতৃত্ব / প্রসব',
    'pt.maternity.desc': 'প্রসব, প্রসবকালীন জটিলতা, গর্ভকালীন জরুরি অবস্থা',
    'pt.paediatric.label': 'শিশু',
    'pt.paediatric.desc': 'শিশুর জরুরি অবস্থা, শিশুর তীব্র জ্বর',
    'pt.poisoning.label': 'বিষক্রিয়া / সাপের কামড়',
    'pt.poisoning.desc': 'খাদ্যে বিষক্রিয়া, রাসায়নিক গ্রহণ, সাপের কামড়',
    'pt.cancer.label': 'ক্যান্সার / টিউমার',
    'pt.cancer.desc': 'অনকোলজি চিকিৎসা, টিউমার, কেমোথেরাপি',
    'pt.trauma.label': 'দুর্ঘটনা / আঘাত',
    'pt.trauma.desc': 'সড়ক দুর্ঘটনা, চাপাপড়া আঘাত, বড় ধরনের আঘাত',
    'pt.other.label': 'অন্যান্য জরুরি',
    'pt.other.desc': 'জ্বর, দাঁত, চোখ বা অন্যান্য জরুরি চিকিৎসা',

    'emergency.hotlineTitle': 'জরুরি যোগাযোগ',
    'emergency.hotline999': 'জাতীয় জরুরি সেবা',
    'emergency.hotline16321': 'স্বাস্থ্য হেল্পলাইন',
    'emergency.hotline199': 'ফায়ার ও অ্যাম্বুলেন্স',
    'emergency.howTitle': 'কীভাবে কাজ করে',
    'emergency.how1': 'আপনার জরুরি সমস্যার ধরন বেছে নিন',
    'emergency.how2': 'আমরা ডাক্তার স্কোর অনুযায়ী হাসপাতাল র‍্যাংক করি',
    'emergency.how3': 'দিকনির্দেশনা বোতামে চাপুন, সঙ্গে সঙ্গে পথ পাবেন',
    'emergency.trustNote': 'সব হাসপাতাল নির্ধারিত ডাক্তারদের দ্বারা রোগীর ফলাফলের ভিত্তিতে রেটিং করা হয়েছে।',

    'hl.title': 'হাসপাতাল নিবন্ধন',
    'hl.subtitle': 'নিবন্ধিত হাসপাতাল পরিচালনা ও অনুসন্ধান করুন',
    'hl.searchPlaceholder': 'নামে হাসপাতাল খুঁজুন...',
    'hl.hospitalsFound': '{n}টি হাসপাতাল পাওয়া গেছে',
    'hl.showing': '{total}টির মধ্যে {shown}টি দেখানো হচ্ছে',
    'hl.page': 'পেজ {page} / {totalPages}',
    'hl.noResults': 'কোনো হাসপাতাল পাওয়া যায়নি',
    'hl.noResultsHint': 'ফিল্টার পরিবর্তন করে আবার চেষ্টা করুন।',
    'hl.deleteConfirm': 'আপনি কি এই হাসপাতাল মুছে দিতে চান?',

    'filters.title': 'ফিল্টার',
    'filters.clearAll': 'সব মুছুন',
    'filters.clearFilters': 'ফিল্টার মুছুন',
    'filters.division': 'বিভাগ',
    'filters.allDivisions': 'সব বিভাগ',
    'filters.district': 'জেলা',
    'filters.allDistricts': 'সব জেলা',
    'filters.upazila': 'উপজেলা',
    'filters.allUpazilas': 'সব উপজেলা',
    'filters.type': 'হাসপাতালের ধরন',
    'filters.allTypes': 'সব ধরন',
    'filters.agency': 'সংস্থা',
    'filters.allAgencies': 'সব সংস্থা',
    'filters.ownership': 'মালিকানা',
    'filters.all': 'সব',
    'filters.private': 'বেসরকারি',
    'filters.public': 'সরকারি',
    'filters.loading': 'ফিল্টার লোড হচ্ছে...',

    'table.hospital': 'হাসপাতাল',
    'table.code': 'কোড',
    'table.type': 'ধরন',
    'table.agency': 'সংস্থা',
    'table.division': 'বিভাগ',
    'table.district': 'জেলা',
    'table.email': 'ইমেইল',
    'table.status': 'অবস্থা',
    'table.actions': 'কার্যক্রম',
    'table.private': 'বেসরকারি',
    'table.public': 'সরকারি',

    'stats.title': 'পরিসংখ্যান সারসংক্ষেপ',
    'stats.subtitle': 'বাংলাদেশে হাসপাতালের বিতরণ',
    'stats.refresh': 'রিফ্রেশ',
    'stats.overview': 'সারসংক্ষেপ',
    'stats.total': 'মোট হাসপাতাল',
    'stats.public': 'সরকারি হাসপাতাল',
    'stats.private': 'বেসরকারি হাসপাতাল',
    'stats.ofTotal': '% মোটের',
    'stats.byType': 'ধরন অনুযায়ী',
    'stats.types': '{n}টি ধরন',
    'stats.byDivision': 'বিভাগ অনুযায়ী',
    'stats.divisions': '{n}টি বিভাগ',
    'stats.colType': 'ধরন',
    'stats.count': 'সংখ্যা',
    'stats.share': 'অংশ',
    'stats.distribution': 'বিতরণ',
    'stats.colDivision': 'বিভাগ',
    'stats.unknown': 'অজানা',
    'stats.noStats': 'কোনো পরিসংখ্যান পাওয়া যায়নি',

    'create.title': 'নতুন হাসপাতাল যোগ করুন',
    'create.subtitle': 'সিস্টেমে একটি নতুন হাসপাতাল নিবন্ধন করুন',
    's1': 'মূল তথ্য',
    'create.name': 'হাসপাতালের নাম',
    'create.namePlaceholder': 'হাসপাতালের নাম দিন',
    'create.nameBangla': 'বাংলায় নাম',
    'create.nameBanglaPlaceholder': 'হাসপাতালের নাম',
    'create.code': 'হাসপাতাল কোড',
    'create.codePlaceholder': 'অনন্য সংখ্যাসূচক কোড',
    'create.email': 'ইমেইল ঠিকানা',
    'create.emailPlaceholder': 'contact@hospital.com',
    's2': 'শ্রেণীবিভাগ',
    'create.type': 'হাসপাতালের ধরন',
    'create.typePlaceholder': 'যেমন: মেডিকেল কলেজ হাসপাতাল',
    'create.agency': 'সংস্থা',
    'create.agencyPlaceholder': 'যেমন: সরকারি, এনজিও, বেসরকারি',
    'create.score': 'মান স্কোর (০–১০০)',
    'create.scoreHint': 'ডাক্তার প্রদত্ত মানের রেটিং, জরুরি অনুসন্ধানে র‍্যাংকিংয়ে ব্যবহৃত',
    'create.private': 'বেসরকারি হাসপাতাল',
    'create.privateHint': 'বেসরকারি মালিকানাধীন হলে চেক করুন',
    's3': 'জরুরি বিশেষত্ব',
    'create.specialtyHint': 'এই হাসপাতাল যে জরুরি বিভাগগুলোতে বিশেষজ্ঞ তা বেছে নিন। জরুরি অনুসন্ধানে এগুলো ব্যবহার করা হয়।',
    's4': 'অবস্থান',
    'create.division': 'বিভাগ',
    'create.divisionPlaceholder': 'যেমন: ঢাকা, চট্টগ্রাম',
    'create.district': 'জেলা',
    'create.districtPlaceholder': 'জেলা দিন',
    'create.upazila': 'উপজেলা',
    'create.upazilaPlaceholder': 'উপজেলা দিন',
    'create.city': 'সিটি কর্পোরেশন',
    'create.paurasava': 'পৌরসভা',
    'create.union': 'ইউনিয়ন',
    'create.applicable': 'প্রযোজ্য হলে',
    'create.lat': 'অক্ষাংশ',
    'create.latPlaceholder': 'যেমন: ২৩.৮১০৩',
    'create.lng': 'দ্রাঘিমাংশ',
    'create.lngPlaceholder': 'যেমন: ৯০.৪১২৫',
    'create.required': '* আবশ্যিক তথ্য',
    'create.submit': 'হাসপাতাল তৈরি করুন',
    'create.creating': 'তৈরি হচ্ছে...',
    'create.nameRequired': 'হাসপাতালের নাম আবশ্যিক',
    'create.codeRequired': 'হাসপাতাল কোড আবশ্যিক',
    'create.success': 'হাসপাতাল সফলভাবে তৈরি হয়েছে!',
    'create.failed': 'হাসপাতাল তৈরি ব্যর্থ হয়েছে।',

    'modal.editTitle': 'হাসপাতাল সম্পাদনা',
    'modal.viewTitle': 'হাসপাতালের বিবরণ',
    'modal.basicInfo': 'মূল তথ্য',
    'modal.hospitalName': 'হাসপাতালের নাম *',
    'modal.nameBangla': 'নাম (বাংলা)',
    'modal.code': 'কোড',
    'modal.email': 'ইমেইল',
    'modal.classification': 'শ্রেণীবিভাগ',
    'modal.agency': 'সংস্থা',
    'modal.type': 'ধরন',
    'modal.ownership': 'মালিকানা',
    'modal.private': 'বেসরকারি',
    'modal.public': 'সরকারি',
    'modal.location': 'অবস্থান',
    'modal.division': 'বিভাগ',
    'modal.district': 'জেলা',
    'modal.upazila': 'উপজেলা',
    'modal.cityCorporation': 'সিটি কর্পোরেশন',
    'modal.paurasava': 'পৌরসভা',
    'modal.union': 'ইউনিয়ন',
    'modal.coordinates': 'স্থানাঙ্ক',
    'modal.quality': 'মান স্কোর',
    'modal.adminScore': 'অ্যাডমিন স্কোর (০–১০০)',
    'modal.record': 'রেকর্ড',
    'modal.created': 'তৈরি',
    'modal.updated': 'শেষ আপডেট',
    'modal.cancel': 'বাতিল',
    'modal.save': 'পরিবর্তন সংরক্ষণ',
    'modal.saving': 'সংরক্ষণ হচ্ছে...',
    'modal.close': 'বন্ধ',
    'modal.viewMap': '🗺️ মানচিত্রে দেখুন',
    'modal.nameRequired': 'হাসপাতালের নাম আবশ্যিক',
    'modal.updatedSuccess': 'হাসপাতাল সফলভাবে আপডেট হয়েছে!',
    'modal.createdSuccess': 'হাসপাতাল সফলভাবে তৈরি হয়েছে!',
    'modal.failed': 'হাসপাতাল সংরক্ষণ ব্যর্থ হয়েছে',
    'modal.privateLabel': 'বেসরকারি হাসপাতাল',

    'error.title': 'কিছু ভুল হয়েছে',
    'error.retry': 'আবার চেষ্টা করুন',
    'error.dismiss': 'বাতিল',

    'auth.appTitle': 'হাসপাতাল ম্যানেজার',
    'auth.appSubtitle': 'বাংলাদেশ হাসপাতাল ব্যবস্থাপনা সিস্টেম',
    'auth.signIn': 'সাইন ইন',
    'auth.createAccount': 'অ্যাকাউন্ট তৈরি',
    'auth.welcomeBack': 'স্বাগতম',
    'auth.signInSubtitle': 'চালিয়ে যেতে আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.signingIn': 'সাইন ইন হচ্ছে…',
    'auth.or': 'অথবা',
    'auth.google': 'Google দিয়ে চালিয়ে যান',
    'auth.connecting': 'সংযুক্ত হচ্ছে…',
    'auth.noAccount': 'অ্যাকাউন্ট নেই?',
    'auth.createOne': 'তৈরি করুন',
    'auth.createTitle': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.createSubtitle': 'হাসপাতাল ম্যানেজার অ্যাক্সেস করতে নিবন্ধন করুন',
    'auth.firstName': 'প্রথম নাম',
    'auth.lastName': 'শেষ নাম',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.pwPlaceholder': 'কমপক্ষে ৬ অক্ষর',
    'auth.creatingAccount': 'অ্যাকাউন্ট তৈরি হচ্ছে…',
    'auth.hasAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'auth.signInLink': 'সাইন ইন',
    'auth.footer': 'বাংলাদেশ হাসপাতাল ব্যবস্থাপনা সিস্টেম',
    'auth.err.fillAll': 'সব তথ্য পূরণ করুন।',
    'auth.err.invalidCred': 'ইমেইল বা পাসওয়ার্ড ভুল।',
    'auth.err.tooMany': 'অনেকবার ব্যর্থ হয়েছেন। পরে আবার চেষ্টা করুন।',
    'auth.err.fillAllRequired': 'সব আবশ্যিক তথ্য পূরণ করুন।',
    'auth.err.pwLength': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে।',
    'auth.err.pwMatch': 'পাসওয়ার্ড মিলছে না।',
    'auth.err.emailExists': 'এই ইমেইলে ইতিমধ্যে একটি অ্যাকাউন্ট আছে।',
    'auth.err.diffCred': 'এই ইমেইলে ইতিমধ্যে একটি অ্যাকাউন্ট আছে। পাসওয়ার্ড দিয়ে সাইন ইন করুন।',
    'auth.err.googleFail': 'Google সাইন-ইন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'auth.err.loginFail': 'লগইন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'auth.err.registerFail': 'নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en')

  useEffect(() => {
    localStorage.setItem('lang', lang)
    document.documentElement.lang = lang
  }, [lang])

  const toggleLang = useCallback(() => {
    setLang(prev => prev === 'en' ? 'bn' : 'en')
  }, [])

  const t = useCallback((key, vars = {}) => {
    let str = TRANSLATIONS[lang][key] ?? TRANSLATIONS['en'][key] ?? key
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(`{${k}}`, v)
    })
    return str
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
